'use strict';

import { alert } from '../components/laserweb.js';
import { gStatic,rectFrame, rectFrame6, framePath, operator, shapeTemplats, allShapesSVG } from '../data/staticData.js'



export function  getG(content){
    const startIndex = content.indexOf('<g');
    const endIndex = content.indexOf('/g>');
    const G = content.substring(startIndex, endIndex + 3);
    return G;
}

export function getGIndex(content) {
    const startIndex = content.indexOf('<g');
    const endIndex = content.indexOf('/g>');
    const G = content.substring(startIndex, endIndex + 3);
    return [startIndex,endIndex];
}

export function getSVGOpenClose(content){
    const endIndex = content.indexOf('</svg>');
    //what if content.indexOf returs -1

    var startIndex = content.indexOf('www.w3.org/2000/svg">');
    if(startIndex != -1)
        startIndex = startIndex + 21;
    return [startIndex, endIndex];
}
//to find the openining and closing of <svg> tag for files generated by convertio api
export function getSVGOpenCloseAPI(content) {
    const endIndex = content.indexOf('</svg>');
    //what if content.indexOf returs -1

    var startIndex = content.indexOf('preserveAspectRatio="xMidYMid meet"');
    if (startIndex != -1)
        startIndex = startIndex + 37;
    return [startIndex, endIndex];
}

export function getGPosition(string, subString, index) {
    return string.split(subString, index).join(subString).length;
}

export function findStartEndIndices(string, substring){
    const startIndex = string.indexOf(substring);
    const endIndex = string.indexOf('"', startIndex + 11);
    return [startIndex, endIndex]

}
export function findStartEndIndicesTranslate(string, substring) {
    const startIndex = string.indexOf(substring);
    const endIndex = string.indexOf('"', startIndex +15);
    return [startIndex, endIndex]

}
export function getPosition(string, subString, index) {
    return string.split(subString, index).join(subString).length;
}

export function getDimensionAPI(svg) {
    let widthStart = getPosition(svg, '"', 13);
    let widthFin = getPosition(svg, '"', 14);
    let width = svg.slice(widthStart + 1, widthFin)
    let heightStart = getPosition(svg, '"', 15);
    let heightEnd = getPosition(svg, '"', 16);
    let height = svg.slice(heightStart + 1, heightEnd)
    console.log('width : ', width, 'height:', height);
    return [parseFloat(width), parseFloat(height)];
}

export function getDimension(svgObject) {
    let widthStart = getPosition(svgObject, '"', 1);
    let widthFin = getPosition(svgObject, '"', 2);
    let width = svgObject.slice(widthStart + 1, widthFin)
    let heightStart = getPosition(svgObject, '"', 3);
    let heightEnd = getPosition(svgObject, '"', 4);
    let height = svgObject.slice(heightStart + 1, heightEnd)
    console.log('width : ', width, 'height:', height);
    return [parseFloat(width), parseFloat(height)];
}

export function getDimensionGeneral(svgObject){
    const widthStart = svgObject.indexOf('width="') + 6;
    const widthFin = svgObject.indexOf('"', widthStart + 1);
    const width = svgObject.slice(widthStart + 1, widthFin);

    const heightIndex = svgObject.indexOf('height="') + 7;
    const heightFin = svgObject.indexOf('"', heightIndex + 1);
    const height = svgObject.slice(heightIndex + 1, heightFin);
    return [parseFloat(width), parseFloat(height), width, height];
}

export function getDimensionStr(svgObject) {
    let widthStart = getPosition(svgObject, '"', 1);
    let widthFin = getPosition(svgObject, '"', 2);
    let width = svgObject.slice(widthStart + 1, widthFin)
    let heightStart = getPosition(svgObject, '"', 3);
    let heightEnd = getPosition(svgObject, '"', 4);
    let height = svgObject.slice(heightStart + 1, heightEnd)
    console.log('width : ', width, 'height:', height);
    return [width, height];
}

export function calcMargins(svgOutput) {

    let dims = getDimension(this.state.svgOutpout);
    let mmDims = dims.map(n => n / operator);
    let margins = [(42 - mmDims[0]) / 2, (41 - mmDims[1]) / 2];
    return margins;
}

export function validateLayout(layout, text, maxLines) { //// add another condition which is if the number of lines is bigger than the number of words
    return layout.lines.length > maxLines ? false : true;
}

export function isWrappedWord(layout, text) {
    let result = true;
    var words = text.split(" ");
    words.forEach((word) => {
        layout.lines.forEach((line, j) => {
            console.log('end', layout.lines[j].end, 'start', layout.lines[j].start, 'word length:', word.length);
            if (layout.lines[j].end - layout.lines[j].start < word.length) {
                result = false;
            }
        })
    })
    return true;
}
export function rotateRect(svgFile) {
    var result = svgFile;
    const tansformIndex = findStartEndIndices(svgFile, 'transform="');
    const transform = ' transform=" rotate(-90 280 200) translate(0.000000,390.000000) scale(0.100000,-0.100000) ';//-0.0215,-0.0215 those has to be dynamically
    var final5 = result.replace(result.substring(tansformIndex[0], tansformIndex[1]), transform);
    console.log(result);
    return final5;
}
export function generateSVGGird(svgObject,cState){

    
    const svgDims = getDimensionGeneral(svgObject);
    const activeTemplate = cState.activeTemplate;
    var pcsCount = activeTemplate.pcsCount;
    var svgFileModified;
    const maxDim = Math.max(...svgDims);
    const minDim = Math.min(...svgDims);
    if ([2, 3, 6, 8, 16].indexOf(pcsCount) === -1)
        svgFileModified = svgObject.replace(svgDims[0], '1122.5196').replace(svgDims[0], '1122.5196').replace(svgDims[1], '1587.401').replace(svgDims[1], '1587.401');// we have to change this
    else
        svgFileModified = svgObject.replace(svgDims[0], '1122.5196').replace(svgDims[0], '1122.5196').replace(svgDims[1], '1587.401').replace(svgDims[1], '1587.401');// we have to change this var transformIndex = svgFileModified.indexOf('<g')+2;
    const mmDims = svgDims.map(n => n / operator);
    var transformIndex = svgFileModified.indexOf('<g') + 2;
    var transformIndices = findStartEndIndicesTranslate(svgFileModified,'transform="translate');
    var mainMargin = 600+operator * (activeTemplate.initialMargin[0] - mmDims[0]) / 2;
    var stringMarin = mainMargin.toString();//to be changed according to the shape
    var stringMarginY = activeTemplate.initialMargin[1];//to be changed according to the shape
    //svgDims[1]*scaling[1]=21.80
    console.log('svgDims',svgDims,'percentage 0/1',svgDims[0]/svgDims[1]);
    var factor = activeTemplate.calligraphyFactor*(svgDims[1]/svgDims[0])
    var scalingX = activeTemplate.calligraphyFactor  / svgDims[0];
    var scalingY = factor / svgDims[1];// 4.5,12 should be taken from the state,

    // one line or two line? or how many lines????
    //calligraphyScalingPercetage: [0.02, -0.02],
    //30
    // not adding : replacing 
    //var finalist = svgFileModified.slice(0, transformIndex) + ' transform="translate(' + stringMarin + ',' + stringMarginY + ') scale(' + activeTemplate.textScalingPercetage + ')" ' + svgFileModified.slice(transformIndex);

    // we have to fix this
    //calligraphyScalingPercetage has to be dynamic according to dimensions

    var finalist = svgFileModified.replace(
        svgFileModified.substring(transformIndices[0], transformIndices[1]+2),
         ' transform="translate(' + stringMarin + ',' + stringMarginY + ') scale(' + 
         scalingX + ',-' + scalingY + ')" '
        );
    var theFinal = finalist;
    var closeGIndex = finalist.indexOf('</svg>');
    let k = 0;
    var contentModified;
    var decoration, decoroartionDown;
    var mainG = getG(finalist);
    var gIndices = findStartEndIndicesTranslate(mainG, 'transform="translate');
    theFinal = theFinal.replace(mainG,' ');
    var newG ;
    var shapeFile = cState.shapeFile;
    if ([2, 3, 24].indexOf(pcsCount) !== -1)
        shapeFile = cState.extension + cState.shapeFile;
    fetch(shapeFile)
        .then(resp => resp.text())
        .then(content => {
            // replace the first <G in content with what we want
            for (let i = 0; i < activeTemplate.xCount; i++) {
                for (let j = 0; j < activeTemplate.yCount; j++) {
                    closeGIndex = theFinal.indexOf('</svg>');
                    if (cState.hasDecoration) {
                        decoration = '<g transform="translate(' + activeTemplate.decorationMargin[k] + ') scale(' + activeTemplate.shapeScalingPercentage + ')"><path opacity="0.75" fill="url(#SVGID_1_)" d="M165,52.485c-0.139,0.002-0.27,0.016-0.411,0.016 c-0.539,0-1.052-0.025-1.567-0.052L165,50.472v-2.405l-3.156,3.161l-4.305-4.302l3.853-3.853H165V41.37h-3.608l-3.853-3.848 l4.305-4.309L165,36.378v-2.406l-6.134-6.133h-0.033L165,21.674v-2.406l-3.156,3.165l-4.305-4.307l3.853-3.85H165v-1.701 h-3.608l-3.853-3.854l4.305-4.301L165,7.582V5.176L159.828,0h-2.411l3.22,3.217l-4.3,4.299l-3.853-3.851V0h-1.698v3.666 l-3.855,3.851l-4.3-4.299L145.85,0h-2.406l-6.208,6.213L131.028,0h-2.411l3.223,3.217l-4.302,4.299l-3.853-3.851V0h-1.694 v3.469c0.218,0.178,0.404,0.368,0.616,0.554c-1.648-1.429-3.513-2.754-5.649-3.93L117.053,0h-10.321 c25.386,6.565,22.77,29.939,22.77,29.939h8.569c0,0,1.746,26.257,26.518,26.257c0.141,0,0.272-0.012,0.411-0.014V52.485z M159.842,42.222l-3.501,3.502l-3.505-3.502l3.502-3.499L159.842,42.222z M150.786,23.179v3.827h-4.779l-3.376-3.378 l4.3-4.302L150.786,23.179z M148.133,18.126l3.502-3.499l3.505,3.499l-3.505,3.502L148.133,18.126z M150.786,28.637v3.83 l-3.855,3.853l-4.3-4.299l3.376-3.384H150.786z M151.635,34.019l3.5,3.503l-3.5,3.499l-3.502-3.499L151.635,34.019z  M160.637,32.021l-4.3,4.299l-3.853-3.853v-3.83h4.777L160.637,32.021z M160.637,23.628l-3.377,3.378h-4.777v-3.827 l3.857-3.853L160.637,23.628z M159.842,13.423l-3.501,3.502l-3.505-3.502l3.502-3.505L159.842,13.423z M151.635,5.219 l3.5,3.502l-3.5,3.499l-3.502-3.499L151.635,5.219z M150.434,13.423l-3.503,3.502l-3.501-3.502l3.501-3.505L150.434,13.423z  M138.052,7.801l3.376-3.381l4.305,4.301l-3.854,3.854h-3.827V7.801z M138.052,14.276h3.825l3.856,3.85l-4.305,4.307 l-3.376-3.384V14.276z M133.043,4.42l3.38,3.381v4.774h-3.826l-3.854-3.854L133.043,4.42z M128.457,10.84l2.584,2.583 l-0.758,0.762C129.76,13.061,129.147,11.941,128.457,10.84z M132.801,22.19c-0.363-2.045-0.937-4.181-1.792-6.331l1.588-1.584 h3.826v4.773l-3.38,3.384L132.801,22.19z M141.76,29.688l-0.251-3.441c0,0-5.876,0-8.241,0 c-0.025-0.499-0.061-1.007-0.114-1.524l4.082-4.084l7.199,7.202h-0.027l-2.581,2.575 C141.782,30.028,141.762,29.773,141.76,29.688z M142.585,34.369l3.149,3.153l-1.549,1.547 C143.458,37.393,142.945,35.776,142.585,34.369z M144.953,40.701l1.977-1.977l3.503,3.499l-2.731,2.73 C146.595,43.587,145.686,42.141,144.953,40.701z M148.827,46.231l2.808-2.804l3.505,3.499l-2.451,2.444 C151.214,48.458,149.93,47.392,148.827,46.231z M160.38,52.165l-0.006-0.002c-2.322-0.371-4.359-1.041-6.142-1.931 l2.108-2.101l4.033,4.032c0.017,0.002,0.032,0.008,0.049,0.011C160.41,52.171,160.391,52.171,160.38,52.165z"/><linearGradient id="SVGID_2_" gradientUnits="userSpaceOnUse" x1="315.2232" y1="-6.5167" x2="128.7738" y2="162.3331" gradientTransform="matrix(-1 0 0 -1 293.373 176.5627)"><stop  offset="0" style="stop-color:#FFFFFF"/><stop  offset="1" style="stop-color:#696969"/></linearGradient></g>';
                        decoroartionDown = '<g transform="translate(' + activeTemplate.decorationDMargin[k] + ') scale(' + activeTemplate.shapeScalingPercentage + ')"><path opacity="0.75" fill="url(#SVGID_2_)" d="M0,112.514c0.139-0.003,0.27-0.016,0.411-0.016 c0.539,0,1.052,0.024,1.567,0.052L0,114.527v2.406l3.156-3.161l4.305,4.302l-3.853,3.854H0v1.702h3.608l3.853,3.848 l-4.305,4.309L0,128.621v2.406l6.134,6.133h0.033L0,143.326v2.406l3.156-3.165l4.305,4.305l-3.853,3.851H0v1.702h3.608 l3.853,3.853l-4.305,4.301L0,157.417v2.406l5.172,5.176h2.411l-3.22-3.216l4.3-4.299l3.853,3.849v3.666h1.698v-3.666 l3.855-3.849l4.3,4.299l-3.219,3.216h2.406l6.208-6.213l6.208,6.213h2.411l-3.223-3.216l4.302-4.299l3.853,3.849V165h1.694 v-3.471c-0.218-0.177-0.404-0.367-0.616-0.554c1.648,1.429,3.513,2.755,5.649,3.93L47.947,165h10.321 c-25.386-6.566-22.77-29.94-22.77-29.94h-8.569c0,0-1.746-26.257-26.518-26.257c-0.141,0-0.272,0.011-0.411,0.013V112.514z M5.158,122.777l3.501-3.501l3.505,3.501l-3.502,3.498L5.158,122.777z M14.214,141.819v-3.827h4.779l3.376,3.379l-4.3,4.302 L14.214,141.819z M16.867,146.873l-3.502,3.5l-3.505-3.5l3.505-3.501L16.867,146.873z M14.214,136.362v-3.83l3.855-3.853 l4.3,4.299l-3.376,3.384H14.214z M13.365,130.98l-3.5-3.503l3.5-3.5l3.502,3.5L13.365,130.98z M4.363,132.978l4.3-4.299 l3.853,3.853v3.83H7.739L4.363,132.978z M4.363,141.371l3.377-3.379h4.777v3.827l-3.857,3.854L4.363,141.371z M5.158,151.576 l3.501-3.501l3.505,3.501l-3.502,3.505L5.158,151.576z M13.365,159.781l-3.5-3.503l3.5-3.498l3.502,3.498L13.365,159.781z  M14.566,151.576l3.503-3.501l3.501,3.501l-3.501,3.505L14.566,151.576z M26.948,157.198l-3.376,3.381l-4.305-4.301 l3.854-3.853h3.827V157.198z M26.948,150.724h-3.825l-3.856-3.851l4.305-4.305l3.376,3.384V150.724z M31.957,160.578 l-3.38-3.381v-4.773h3.826l3.853,3.853L31.957,160.578z M36.543,154.159l-2.584-2.583l0.758-0.762 C35.24,151.939,35.853,153.058,36.543,154.159z M32.199,142.809c0.363,2.045,0.937,4.181,1.792,6.331l-1.588,1.584h-3.826 v-4.773l3.38-3.384L32.199,142.809z M23.24,135.311l0.251,3.442c0,0,5.876,0,8.241,0c0.025,0.5,0.061,1.007,0.114,1.524 l-4.082,4.083l-7.199-7.201h0.027l2.581-2.575C23.218,134.971,23.238,135.226,23.24,135.311z M22.415,130.63l-3.149-3.153 l1.549-1.547C21.542,127.606,22.055,129.224,22.415,130.63z M20.047,124.298l-1.977,1.977l-3.503-3.498l2.731-2.73 C18.405,121.412,19.314,122.857,20.047,124.298z M16.173,118.768l-2.808,2.805l-3.505-3.5l2.451-2.444 C13.786,116.541,15.07,117.606,16.173,118.768z M4.62,112.833l0.006,0.003c2.322,0.371,4.359,1.041,6.142,1.93l-2.108,2.101 l-4.033-4.032c-0.017-0.003-0.032-0.008-0.049-0.011C4.59,112.828,4.609,112.828,4.62,112.833z"/></g>';
                    }
                    else {
                        decoration = '';
                        decoroartionDown = '';
                    }
                    var marginX = activeTemplate.shapeMarginsBase[0] + i * activeTemplate.shapeMarginsBase[2];
                    var marginY = activeTemplate.shapeMarginsBase[1] + j * activeTemplate.shapeMarginsBase[3];
                    var margins = marginX.toString() + ',' + marginY.toString();
                    var marginsC = (marginX + activeTemplate.calligraphyMargins[0]).toString() + ',' + (marginY + activeTemplate.calligraphyMargins[1]).toString();// 100 and 300 should be dynamic
                    newG = mainG.replace(mainG.substring(gIndices[0], gIndices[1] + 2), 'transform="translate(' + marginsC + ') scale(' + scalingX + ',-' + scalingY + ')" ');
                    //contentModified = content.replace('<g id="bostani">', '<g id="bostani" transform="translate(' + activeTemplate.shapeMargins[k] + ') scale('+activeTemplate.shapeScalingPercentage+')">');// we have to change this
                    contentModified = content.replace('<g id="bostani">', '<g id="bostani" transform="translate(' + margins + ') scale(' + activeTemplate.shapeScalingPercentage + ')">');// we have to change this
                    theFinal = theFinal.slice(0, closeGIndex) + contentModified + decoration + newG + decoroartionDown + theFinal.slice(closeGIndex);
                    k++;
                }
            }
            closeGIndex = theFinal.indexOf('</svg>');

            if ([2, 3, 6, 8, 16].indexOf(pcsCount) === -1)
                theFinal = theFinal.slice(0, closeGIndex) + rectFrame + theFinal.slice(closeGIndex);
            else
                theFinal = theFinal.slice(0, closeGIndex) + rectFrame6 + theFinal.slice(closeGIndex);
            if ([2, 3, 6, 8, 16].indexOf(pcsCount) !== -1) {
                const rotateStatement = '<g transform="rotate(-90 280 200)  translate(479.3,1041.949) scale(-1,-1 )">';
                const svgIndices = getSVGOpenCloseAPI(theFinal);
                var anotherStep = theFinal.slice(0, svgIndices[0]) + rotateStatement + theFinal.slice(svgIndices[0]);
                theFinal = anotherStep.slice(0, svgIndices[1] + rotateStatement.length) + '</g>' + anotherStep.slice(svgIndices[1] + rotateStatement.length);
            }

            var svgElement = document.getElementById("boxTemplate");
            svgElement.setAttribute('href', 'data:text/plain;chartset=utf-8,' + encodeURIComponent(theFinal));
            alert('File is ready');
            svgElement.setAttribute('download', 'File.svg');
        });
    return theFinal;
}
export function minimizeSvgFileRect(svgFile, percentageX, percentageY, scaleX, scaleY, moldName) {
    //const ourFramePath = '<g stroke-linecap="round" fill-rule="evenodd" font-size="12px" stroke="#000" stroke-width="0.25mm" fill="none" style="fill:none;stroke:#000000;stroke-width:0.25mm" id="layer1" transform="matrix(2.8321,0,0,2.8321,2,-161)"><path d="m 233.83379,67.373184 c -2.53989,0.0018 -2.01422,0.247614 -2.01242,3.001398 0.002,2.761509 -2.23509,5.001401 -4.99667,5.003306 -2.76151,0.0018 -5.0014,-2.2352 -5.00331,-4.99678 -0.002,-2.438506 0.43819,-3.000199 -1.39322,-2.998999 l -29.58928,0.01979 c -1.57229,0.0011 -1.01899,0.713105 -1.01751,3.000798 0.002,2.76158 -2.23499,5.001401 -4.99661,5.003306 -2.76168,0.0018 -5.00157,-2.2352 -5.0033,-4.996709 -0.002,-2.569316 0.58282,-3.00041 -1.50619,-2.999105 l -29.08229,0.01951 c -2.01362,0.0014 -1.4133,0.467889 -1.4116,3.000904 0.002,2.761579 -2.2351,5.001507 -4.99661,5.003306 -2.76161,0.0018 -5.0015,-2.23513 -5.00341,-4.996709 -0.002,-2.664496 0.83831,-3.000516 -1.46477,-2.998894 l -29.06042,0.0193 c -2.04481,0.0014 -1.47641,0.452896 -1.47468,3.001081 0.002,2.761615 -2.23503,5.001507 -4.99671,5.003412 -2.76151,0.0018 -5.001402,-2.2352 -5.003201,-4.996815 -0.0018,-2.426476 0.550298,-3.000375 -1.258499,-2.99907 l -29.269619,0.01937 c -2.285682,0.0018 -1.473588,0.343923 -1.471789,3.00101 0.0018,2.761614 -2.235094,5.001506 -4.996709,5.003411 -2.76158,0.0018 -5.001471,-2.2352 -5.003376,-4.996815 -0.0018,-2.623678 0.825888,-3.00048 -1.382607,-2.998999 l -30.757812,0.0206 c -2.419703,0.0014 -1.361405,0.288889 -1.359676,3.000692 0.0019,2.761721 -2.235129,5.001613 -4.996603,5.003412 -4.260321,0.0028 -5.4871056,-0.635706 -5.4989942,1.399399 l 0.017568,26.354686 c 0.00113,1.74092 3.1126292,1.24742 5.5007232,1.2459 2.761579,-0.002 5.001507,2.23503 5.003376,4.99671 0.0018,2.76141 -2.235094,5.0014 -4.996568,5.00331 -2.509625,0.002 -5.5004051,-0.74369 -5.4992057,1.22319 l 0.019085,28.53069 c 0.00109,1.74092 3.1124877,1.24763 5.5006867,1.2459 2.761615,-0.002 5.001507,2.23509 5.003412,4.99671 0.0017,2.76151 -2.235094,5.00151 -4.996603,5.00341 -2.509591,0.002 -5.5005812,-0.74372 -5.4992054,1.22308 l 0.019015,28.53101 c 0.0012,1.74089 3.1124884,1.24739 5.5007934,1.24591 2.761509,-0.002 5.001401,2.23498 5.003306,4.9967 0.0018,2.76141 -2.235094,5.00141 -4.996497,5.0032 -2.509697,0.002 -5.5006174,-0.74362 -5.4992063,1.2233 0.00589,8.9566 0.011818,17.91321 0.017886,26.86988 0.014323,1.9957 1.2659083,0.90992 5.5004053,0.9071 2.761721,-0.002 5.001613,2.23502 5.003412,4.9966 0.0016,2.4421 -0.958603,3.0226 0.459987,2.9996 l 30.735199,-0.0205 c 2.399629,-0.002 2.306919,0.11 2.304908,-3.00168 -0.0018,-2.7614 2.2352,-5.00129 4.996604,-5.0032 2.761615,-0.002 5.001506,2.2351 5.003411,4.99668 0.0018,2.8334 0.417689,2.99229 1.100702,2.99931 l 29.636684,-0.0198 c 1.968395,-0.001 1.264215,-0.4905 1.262486,-3.0009 -0.0018,-2.76151 2.23513,-5.0013 4.996601,-5.0032 2.76172,-0.002 5.00151,2.23509 5.00331,4.9966 0.001,1.80898 -0.42859,3.00031 0.4978,2.99971 l 30.83239,-0.0206 c 0.9549,-7e-4 0.67102,-1.16702 0.66982,-3.00062 -0.002,-2.76147 2.2352,-5.0002 4.9966,-5.002 2.76158,-0.002 5.00151,2.23383 5.00338,4.99541 0.001,2.12181 -0.39578,3.0003 0.92802,2.99942 l 29.85449,-0.0199 c 1.9668,-0.001 1.21909,-0.49111 1.2175,-3.0008 -0.002,-2.76148 2.2351,-5.0014 4.99671,-5.0032 2.76148,-0.002 5.0014,2.23502 5.0032,4.9966 0.002,2.38831 -0.48919,3.0003 1.25169,2.99911 l 30.1975,-0.0202 c 1.38522,0.0433 0.55252,-0.49492 0.55079,-3.00041 -0.002,-2.76151 2.2352,-5.0014 4.99671,-5.0032 2.76161,-0.002 5.00151,2.23498 5.00331,4.99671 0.002,2.81177 -0.35631,2.95599 1.10179,2.99917 10.319,-0.007 20.63799,-0.0137 30.95699,-0.0206 2.47791,-0.002 1.44311,-0.2666 1.44142,-3.00098 -0.002,-2.76151 2.23509,-5.0014 4.9966,-5.0033 4.15798,-0.003 5.4876,0.83199 5.49921,-1.13482 -0.006,-8.88319 -0.0119,-17.76638 -0.0178,-26.6495 -10e-4,-1.96677 -2.99131,-1.21747 -5.5009,-1.21578 -2.7614,0.002 -5.00129,-2.2352 -5.0032,-4.99671 -0.002,-2.76161 2.23509,-5.0015 4.99671,-5.0033 2.38809,-0.001 5.50019,0.48761 5.49899,-1.25328 l -0.019,-28.5309 c -10e-4,-1.96681 -2.9912,-1.21751 -5.50079,-1.21582 -2.76151,0.002 -5.00141,-2.2352 -5.00331,-4.99671 -0.002,-2.76158 2.23509,-5.0015 4.99671,-5.00337 2.3882,-0.001 5.5003,0.48768 5.4991,-1.25321 l -0.0191,-28.5308 c -0.001,-1.9668 -2.99109,-1.2175 -5.50082,-1.21581 -2.76148,0.002 -5.0013,-2.2352 -5.00321,-4.99671 -0.002,-2.76158 2.23513,-5.00147 4.99661,-5.00327 2.3883,-0.002 5.5003,0.48757 5.4992,-1.25331 l -0.018,-26.839617 c -0.0141,-1.966771 -1.34249,-0.909779 -5.5004,-0.907203 -2.76158,0.0018 -5.00162,-2.234883 -5.00341,-4.996498 -0.002,-2.73438 1.03261,-3.000692 -1.4453,-2.998999 z" vector-effect="non-scaling-stroke" id="path5" /></g>';
    const ourFramePath = '<g><path fill-rule="evenodd" clip-rule="evenodd" fill="none" stroke="#030000" stroke-width="2.5087" stroke-linecap="round" stroke-miterlimit="10" d="M658.381,21.949c-7.193,0.005-5.705,0.659-5.699,7.983c0.006,7.347-6.33,13.305-14.152,13.31 c-7.82,0.006-14.164-5.945-14.17-13.292c-0.004-6.486,1.242-7.98-3.943-7.978l-83.801,0.053c-4.453,0.003-2.887,1.897-2.883,7.984 c0.006,7.345-6.33,13.304-14.15,13.309c-7.82,0.005-14.164-5.946-14.17-13.292c-0.006-6.834,1.65-7.981-4.266-7.979l-82.363,0.052 c-5.703,0.004-4.004,1.245-3.998,7.983c0.006,7.346-6.33,13.305-14.15,13.31c-7.822,0.005-14.166-5.945-14.17-13.292 c-0.006-7.088,2.374-7.981-4.149-7.978l-82.302,0.052c-5.791,0.003-4.181,1.204-4.176,7.983c0.006,7.346-6.33,13.306-14.151,13.31 c-7.821,0.005-14.165-5.945-14.17-13.292c-0.005-6.455,1.559-7.981-3.564-7.978l-82.894,0.052 c-6.474,0.005-4.174,0.915-4.169,7.983c0.005,7.346-6.33,13.304-14.151,13.31c-7.821,0.005-14.165-5.946-14.17-13.292 c-0.005-6.98,2.339-7.983-3.916-7.978l-87.109,0.054c-6.853,0.004-3.856,0.77-3.851,7.982c0.005,7.347-6.33,13.306-14.151,13.31 c-12.065,0.008-15.54-1.691-15.574,3.723l0.05,70.108c0.003,4.631,8.815,3.318,15.579,3.314c7.821-0.005,14.165,5.945,14.17,13.292 c0.005,7.346-6.33,13.305-14.15,13.31c-7.108,0.005-15.578-1.979-15.574,3.254l0.054,75.896c0.003,4.632,8.815,3.318,15.579,3.314 c7.821-0.006,14.165,5.945,14.17,13.293c0.004,7.346-6.33,13.304-14.151,13.309c-7.107,0.006-15.579-1.979-15.575,3.254 l0.054,75.897c0.003,4.633,8.814,3.318,15.579,3.315c7.821-0.005,14.165,5.944,14.17,13.291c0.005,7.346-6.33,13.305-14.151,13.311 c-7.107,0.006-15.578-1.979-15.574,3.254c0.017,23.826,0.034,47.652,0.051,71.479c0.041,5.309,3.585,2.421,15.578,2.412 c7.821-0.005,14.165,5.946,14.17,13.292c0.004,6.496-2.715,8.04,1.303,7.979l87.045-0.055c6.796-0.005,6.533,0.292,6.527-7.984 c-0.005-7.347,6.331-13.305,14.151-13.311c7.821-0.004,14.165,5.946,14.17,13.292c0.006,7.539,1.183,7.961,3.118,7.979 l83.934-0.053c5.575-0.003,3.58-1.305,3.575-7.983c-0.005-7.346,6.33-13.304,14.151-13.309c7.822-0.006,14.165,5.944,14.17,13.292 c0.003,4.812-1.214,7.981,1.41,7.979l87.32-0.055c2.705-0.002,1.901-3.104,1.897-7.982c-0.005-7.346,6.331-13.302,14.151-13.308 c7.821-0.004,14.165,5.943,14.171,13.29c0.002,5.645-1.121,7.981,2.629,7.979l84.549-0.053c5.572-0.002,3.453-1.307,3.449-7.982 c-0.006-7.347,6.33-13.304,14.15-13.31c7.82-0.005,14.164,5.945,14.17,13.292c0.006,6.353-1.385,7.981,3.545,7.978l85.521-0.053 c3.924,0.115,1.566-1.317,1.561-7.981c-0.006-7.347,6.332-13.304,14.152-13.31s14.164,5.944,14.168,13.292 c0.006,7.479-1.008,7.863,3.121,7.979c29.225-0.02,58.449-0.037,87.674-0.056c7.018-0.005,4.086-0.709,4.082-7.983 c-0.006-7.346,6.33-13.304,14.15-13.309c11.777-0.008,15.543,2.213,15.576-3.02c-0.018-23.631-0.035-47.261-0.051-70.893 c-0.004-5.231-8.473-3.237-15.58-3.233c-7.82,0.005-14.164-5.947-14.17-13.293c-0.006-7.347,6.33-13.305,14.152-13.31 c6.762-0.004,15.576,1.298,15.572-3.335l-0.053-75.896c-0.002-5.232-8.473-3.238-15.578-3.234 c-7.822,0.006-14.166-5.946-14.17-13.291c-0.006-7.348,6.33-13.306,14.15-13.311c6.764-0.003,15.576,1.298,15.574-3.334 l-0.055-75.897c-0.002-5.231-8.471-3.239-15.578-3.234c-7.822,0.005-14.164-5.946-14.17-13.292 c-0.006-7.347,6.33-13.304,14.15-13.31c6.764-0.005,15.578,1.297,15.574-3.334l-0.051-71.398c-0.039-5.232-3.801-2.42-15.578-2.413 c-7.82,0.004-14.164-5.946-14.17-13.292c-0.006-7.275,2.924-7.982-4.094-7.978L658.381,21.949z"/></g>';
    const fixedWidth = percentageX * scaleX * operator / 12.50; // assuming that there is no white space in the jpg image, if there is white space then it has to be handled differently
    const svgDims = getDimensionGeneral(svgFile);

    // multiplying by 0.9345 is a workaraound till the result comes from them.
    var scalingFactor = 0.93457 * fixedWidth / svgDims[0];// later we will see if 0.93457 needs to be removed
    var scalingFactorY = (scaleY / scaleX) * fixedWidth / svgDims[1] * percentageY;
    
    const viewboxIndex = findStartEndIndices(svgFile, 'viewBox="');
    const final2 = svgFile.replaceAll('fill="#000000"', ' fill="none" ').replaceAll('width="' + svgDims[2] + '"', 'width="800.000000pt"')
        .replaceAll('height="' + svgDims[3] + '"', 'height="535.000000pt"').replaceAll(svgFile.substring(viewboxIndex[0], viewboxIndex[1] + 1), 'viewBox="0 0 800.000000 500.000000"');// have to fix this but how
    const tansformIndex = findStartEndIndices(final2, 'transform="');
    const final3 = final2.replaceAll('stroke="none"', ' stroke="#76C2DA" stroke-width="0.1" ');
    /// original
    const repeatX = 3;
    const repeatY = 6;
    var shiftX = 150.9611671;// this will change according to the mold
    var shiftY = 55.17244096;// this will change according to the mold
    scalingFactor = scalingFactor*2.1;
    scalingFactorY /= 2.1;
    // if the mold is heart or oval or something else
    const transform = ' transform="rotate(-90 280 200) translate(' + shiftX.toString() + ',' + shiftY.toString() + ') scale(-' + scalingFactor + ',-' + scalingFactorY + ') ';//-0.0215,-0.0215 those has to be dynamically
    var final5 = final3.replace(final3.substring(tansformIndex[0], tansformIndex[1]), transform);
    const mainGStart = final5.indexOf('<g');
    // I can add date to here can I ? yes of course
    //const ourDate = '30/6/2021';
    //const date = this.generateDate(ourDate);
    const mainGEnd = final5.indexOf('</g>') + 5;
    const g = final5.substring(mainGStart, mainGEnd);
    
    for (let i = 0; i < 6; i++) {
        for (let j = 0; j < 3; j++) {
            if (j == 0 && i == 0)
                continue;
            var xTransform = parseFloat(shiftX) + j * 147.333 * 0.93457;
            var yTransform = parseFloat(shiftY) + i * 119 ;
            const g1 = g.replace(shiftX.toString(), xTransform).replace(shiftY.toString(), yTransform);
            const insertionIndex = final5.indexOf('</g>') + 4;
            var final = final5.slice(0, insertionIndex) + g1 + final5.slice(insertionIndex);
            final5 = final;
        }

    }

    const insertionIndex = final.indexOf('</g>') + 4;
    var final5 = final.slice(0, insertionIndex) + ourFramePath + final.slice(insertionIndex);
    console.log('Final: ', final5);
    var svgElement = document.getElementById("svgFile");
    svgElement.setAttribute('href', 'data:text/plain;chartset=utf-8,' + encodeURIComponent(final5));

    svgElement.setAttribute('download', 'File.svg');
    return final5;
}


export function minimizeSvgFile(svgFile, percentageX, percentageY,scaleX,scaleY,moldName) {
    // now how scalingFactor,scalingFactorY should be used
    // we have to handle the margin for the oval mold,rectangle mold
    const ourFramePath = '<g stroke-linecap="round" fill-rule="evenodd" font-size="12px" stroke="#000" stroke-width="0.25mm" fill="none" style="fill:none;stroke:#000000;stroke-width:0.25mm" id="layer1" transform="matrix(2.8321,0,0,2.8321,2,-161)"><path d="m 233.83379,67.373184 c -2.53989,0.0018 -2.01422,0.247614 -2.01242,3.001398 0.002,2.761509 -2.23509,5.001401 -4.99667,5.003306 -2.76151,0.0018 -5.0014,-2.2352 -5.00331,-4.99678 -0.002,-2.438506 0.43819,-3.000199 -1.39322,-2.998999 l -29.58928,0.01979 c -1.57229,0.0011 -1.01899,0.713105 -1.01751,3.000798 0.002,2.76158 -2.23499,5.001401 -4.99661,5.003306 -2.76168,0.0018 -5.00157,-2.2352 -5.0033,-4.996709 -0.002,-2.569316 0.58282,-3.00041 -1.50619,-2.999105 l -29.08229,0.01951 c -2.01362,0.0014 -1.4133,0.467889 -1.4116,3.000904 0.002,2.761579 -2.2351,5.001507 -4.99661,5.003306 -2.76161,0.0018 -5.0015,-2.23513 -5.00341,-4.996709 -0.002,-2.664496 0.83831,-3.000516 -1.46477,-2.998894 l -29.06042,0.0193 c -2.04481,0.0014 -1.47641,0.452896 -1.47468,3.001081 0.002,2.761615 -2.23503,5.001507 -4.99671,5.003412 -2.76151,0.0018 -5.001402,-2.2352 -5.003201,-4.996815 -0.0018,-2.426476 0.550298,-3.000375 -1.258499,-2.99907 l -29.269619,0.01937 c -2.285682,0.0018 -1.473588,0.343923 -1.471789,3.00101 0.0018,2.761614 -2.235094,5.001506 -4.996709,5.003411 -2.76158,0.0018 -5.001471,-2.2352 -5.003376,-4.996815 -0.0018,-2.623678 0.825888,-3.00048 -1.382607,-2.998999 l -30.757812,0.0206 c -2.419703,0.0014 -1.361405,0.288889 -1.359676,3.000692 0.0019,2.761721 -2.235129,5.001613 -4.996603,5.003412 -4.260321,0.0028 -5.4871056,-0.635706 -5.4989942,1.399399 l 0.017568,26.354686 c 0.00113,1.74092 3.1126292,1.24742 5.5007232,1.2459 2.761579,-0.002 5.001507,2.23503 5.003376,4.99671 0.0018,2.76141 -2.235094,5.0014 -4.996568,5.00331 -2.509625,0.002 -5.5004051,-0.74369 -5.4992057,1.22319 l 0.019085,28.53069 c 0.00109,1.74092 3.1124877,1.24763 5.5006867,1.2459 2.761615,-0.002 5.001507,2.23509 5.003412,4.99671 0.0017,2.76151 -2.235094,5.00151 -4.996603,5.00341 -2.509591,0.002 -5.5005812,-0.74372 -5.4992054,1.22308 l 0.019015,28.53101 c 0.0012,1.74089 3.1124884,1.24739 5.5007934,1.24591 2.761509,-0.002 5.001401,2.23498 5.003306,4.9967 0.0018,2.76141 -2.235094,5.00141 -4.996497,5.0032 -2.509697,0.002 -5.5006174,-0.74362 -5.4992063,1.2233 0.00589,8.9566 0.011818,17.91321 0.017886,26.86988 0.014323,1.9957 1.2659083,0.90992 5.5004053,0.9071 2.761721,-0.002 5.001613,2.23502 5.003412,4.9966 0.0016,2.4421 -0.958603,3.0226 0.459987,2.9996 l 30.735199,-0.0205 c 2.399629,-0.002 2.306919,0.11 2.304908,-3.00168 -0.0018,-2.7614 2.2352,-5.00129 4.996604,-5.0032 2.761615,-0.002 5.001506,2.2351 5.003411,4.99668 0.0018,2.8334 0.417689,2.99229 1.100702,2.99931 l 29.636684,-0.0198 c 1.968395,-0.001 1.264215,-0.4905 1.262486,-3.0009 -0.0018,-2.76151 2.23513,-5.0013 4.996601,-5.0032 2.76172,-0.002 5.00151,2.23509 5.00331,4.9966 0.001,1.80898 -0.42859,3.00031 0.4978,2.99971 l 30.83239,-0.0206 c 0.9549,-7e-4 0.67102,-1.16702 0.66982,-3.00062 -0.002,-2.76147 2.2352,-5.0002 4.9966,-5.002 2.76158,-0.002 5.00151,2.23383 5.00338,4.99541 0.001,2.12181 -0.39578,3.0003 0.92802,2.99942 l 29.85449,-0.0199 c 1.9668,-0.001 1.21909,-0.49111 1.2175,-3.0008 -0.002,-2.76148 2.2351,-5.0014 4.99671,-5.0032 2.76148,-0.002 5.0014,2.23502 5.0032,4.9966 0.002,2.38831 -0.48919,3.0003 1.25169,2.99911 l 30.1975,-0.0202 c 1.38522,0.0433 0.55252,-0.49492 0.55079,-3.00041 -0.002,-2.76151 2.2352,-5.0014 4.99671,-5.0032 2.76161,-0.002 5.00151,2.23498 5.00331,4.99671 0.002,2.81177 -0.35631,2.95599 1.10179,2.99917 10.319,-0.007 20.63799,-0.0137 30.95699,-0.0206 2.47791,-0.002 1.44311,-0.2666 1.44142,-3.00098 -0.002,-2.76151 2.23509,-5.0014 4.9966,-5.0033 4.15798,-0.003 5.4876,0.83199 5.49921,-1.13482 -0.006,-8.88319 -0.0119,-17.76638 -0.0178,-26.6495 -10e-4,-1.96677 -2.99131,-1.21747 -5.5009,-1.21578 -2.7614,0.002 -5.00129,-2.2352 -5.0032,-4.99671 -0.002,-2.76161 2.23509,-5.0015 4.99671,-5.0033 2.38809,-0.001 5.50019,0.48761 5.49899,-1.25328 l -0.019,-28.5309 c -10e-4,-1.96681 -2.9912,-1.21751 -5.50079,-1.21582 -2.76151,0.002 -5.00141,-2.2352 -5.00331,-4.99671 -0.002,-2.76158 2.23509,-5.0015 4.99671,-5.00337 2.3882,-0.001 5.5003,0.48768 5.4991,-1.25321 l -0.0191,-28.5308 c -0.001,-1.9668 -2.99109,-1.2175 -5.50082,-1.21581 -2.76148,0.002 -5.0013,-2.2352 -5.00321,-4.99671 -0.002,-2.76158 2.23513,-5.00147 4.99661,-5.00327 2.3883,-0.002 5.5003,0.48757 5.4992,-1.25331 l -0.018,-26.839617 c -0.0141,-1.966771 -1.34249,-0.909779 -5.5004,-0.907203 -2.76158,0.0018 -5.00162,-2.234883 -5.00341,-4.996498 -0.002,-2.73438 1.03261,-3.000692 -1.4453,-2.998999 z" vector-effect="non-scaling-stroke" id="path5" /></g>';
    const fixedWidth = percentageX * scaleX * operator / 12.50; // assuming that there is no white space in the jpg image, if there is white space then it has to be handled differently
    //const scalingStr = 
    const svgDims = getDimensionGeneral(svgFile);
    const scalingFactor = fixedWidth / svgDims[0];
    //this should be multipied by some factor 
    const scalingFactorY = (scaleY/scaleX)*fixedWidth / svgDims[1] * percentageY;

    console.log('svgFile:', svgFile);
    const viewboxIndex = findStartEndIndices(svgFile, 'viewBox="');
    const final2 = svgFile.replaceAll('fill="#000000"', ' fill="none" ').replaceAll('width="' + svgDims[2] + '"', 'width="800.000000pt"')
        .replaceAll('height="' + svgDims[3] + '"', 'height="535.000000pt"').replaceAll(svgFile.substring(viewboxIndex[0], viewboxIndex[1] + 1), 'viewBox="0 0 800.000000 500.000000"');// have to fix this but how
    const tansformIndex = findStartEndIndices(final2, 'transform="');
    const final3 = final2.replaceAll('stroke="none"', ' stroke="#76C2DA" stroke-width="0.1" ');
    /// original
    var shiftX = 147.9611671;// this will change according to the mold
    var shiftY = 130.17244096;// this will change according to the mold
    // if the mold is heart or oval or something else
    if(moldName == "Oval" ){
        shiftX = 156;        
        shiftY = 121;
    }
    else if(moldName == "Heart"){
        shiftX = 151;
        shiftY = 119;
    }
    const transform = ' transform="translate(' + shiftX.toString() + ',' + shiftY.toString() +') scale(-' + scalingFactor + ',-' + scalingFactorY + ') ';//-0.0215,-0.0215 those has to be dynamically
    var final5 = final3.replace(final3.substring(tansformIndex[0], tansformIndex[1]), transform);
    const mainGStart = final5.indexOf('<g');
    // I can add date to here can I ? yes of course
    //const ourDate = '30/6/2021';
    //const date = this.generateDate(ourDate);
    const mainGEnd = final5.indexOf('</g>') + 5;
    const g = final5.substring(mainGStart, mainGEnd);
    for (let i = 0; i < 4; i++) {
        for (let j = 0; j < 6; j++) {
            if (j == 0 && i == 0)
                continue;
            var xTransform = parseFloat(shiftX) + j * 119;
            var yTransform = parseFloat(shiftY) + i * 116.5;
            const g1 = g.replace(shiftX.toString(), xTransform).replace(shiftY.toString(), yTransform);
            const insertionIndex = final5.indexOf('</g>') + 4;
            var final = final5.slice(0, insertionIndex) + g1 + final5.slice(insertionIndex);
            final5 = final;
        }

    }

    const insertionIndex = final.indexOf('</g>') + 4;
    var final5 = final.slice(0, insertionIndex) + ourFramePath + final.slice(insertionIndex);
    console.log('Final: ', final5);
    var svgElement = document.getElementById("svgFile");
    svgElement.setAttribute('href', 'data:text/plain;chartset=utf-8,' + encodeURIComponent(final5));

    svgElement.setAttribute('download', 'File.svg');
    return final5;
}

export function removeBlanks(canvas, imgWidth, imgHeight) {
    const context = canvas.getContext("2d");

    var imageData = context.getImageData(0, 0, imgWidth, imgHeight),
        data = imageData.data,
        getRBG = function (x, y) {
            var offset = imgWidth * y + x;
            return {
                red: data[offset * 4],
                green: data[offset * 4 + 1],
                blue: data[offset * 4 + 2],
                opacity: data[offset * 4 + 3]
            };
        },
        isWhite = function (rgb) {
            // many images contain noise, as the white is not a pure #fff white
            return rgb.red > 210 && rgb.green > 210 && rgb.blue > 210;
        },
        scanY = function (fromTop) {
            var offset = fromTop ? 1 : -1;

            // loop through each row
            for (var y = fromTop ? 0 : imgHeight - 1; fromTop ? (y < imgHeight) : (y > -1); y += offset) {

                // loop through each column
                for (var x = 0; x < imgWidth; x++) {
                    var rgb = getRBG(x, y);
                    if (!isWhite(rgb)) {
                        return y;
                    }
                }
            }
            return null; // all image is white
        },
        scanX = function (fromLeft) {
            var offset = fromLeft ? 1 : -1;

            // loop through each column
            for (var x = fromLeft ? 0 : imgWidth - 1; fromLeft ? (x < imgWidth) : (x > -1); x += offset) {

                // loop through each row
                for (var y = 0; y < imgHeight; y++) {
                    var rgb = getRBG(x, y);
                    if (!isWhite(rgb)) {
                        return x;
                    }
                }
            }
            return null; // all image is white
        };
    var inMemCanvas = document.createElement('canvas');
    var inMemCtx = inMemCanvas.getContext('2d');
    var cropTop = scanY(true),
        cropBottom = scanY(false),
        cropLeft = scanX(true),
        cropRight = scanX(false),
        cropWidth = cropRight - cropLeft,
        cropHeight = cropBottom - cropTop;

    //var $croppedCanvas = $("<canvas>").attr({ width: cropWidth, height: cropHeight });
    inMemCanvas.width = cropWidth;
    inMemCanvas.height = cropHeight;
    inMemCtx.drawImage(canvas,
        cropLeft, cropTop, cropWidth, cropHeight,
        0, 0, cropWidth, cropHeight);
    canvas.width = cropWidth;
    canvas.height = cropHeight;

    context.drawImage(inMemCanvas, 0, 0);
    return [cropLeft, cropTop, cropRight, cropBottom, cropWidth, cropHeight];
};

export function detectX() {
    var canvas = document.getElementById("canvas");
    var ctx = canvas.getContext("2d");
    const img = document.getElementById("testXPos");//eeveelutions  //eeveelutions
    ctx.drawImage(img, 0, 0);
    var imgData = ctx.getImageData(0, 0, canvas.width, canvas.height);
    var locations = []; //
    for (var i = 0; i < imgData.data.length; i += 4) {
        if (imgData.data[i] > 220 && imgData.data[i + 1] < 230) {
            locations.push(i / 4);
            imgData.data[i] = 255;
            imgData.data[i + 1] = 255;
            imgData.data[i + 2] = 255;
            imgData.data[i + 3] = 255;
        }
    }
    console.log('the locations are ', locations);
    ctx.putImageData(imgData, 0, 0);
}